Задачи с массивами
js-tasks-ru/js-20200928_yuriy-sh pull request #2
Opened 2020-10-02 17:38 UTC by yurishibaev

2020-10-02 17:47 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-03 11:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const sorted = arr.slice();
в этом решении есть несколько проблема - данные всегда сортируются по `asc` и только после этого происходит проверка `param === 'desc'` и в случае если она ложная, происходит `sorted.reverse()`

Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-10-03 11:20 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const sorted = arr.slice();
также подумайте над ситуацией, когда вызов функции будет произведет со вторым аргументом, которые будет отличным от `asc` или `desc`:
```
sortStrings([], 'foo');
```

2020-10-03 11:20 UTC, dosandk requested changes
необходимо исправить решение `sortStrings`

2020-10-05 14:13 UTC, yurishibaev commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const sorted = arr.slice();
function sortStrings(arr, param = 'asc') { 
const sorted = arr.slice(); 
  if (param === 'asc') {
    sorted.sort( (a, b) => a.localeCompare(b, ['ru', 'en'], {caseFirst: 'upper'}) ); 
  } else if (param === 'desc') {
   sorted.sort( (a, b) => b.localeCompare(a, ['ru', 'en'], {caseFirst: 'upper'}) ); 
  };
 return sorted;
}

2020-10-05 14:14 UTC, yurishibaev commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const sorted = arr.slice();
Ок. Можно и так, как вы сказали, не проблема. Просто я не стал заморачиваться на скорость и некорректные параметры. Запушить смогу только позже

2020-10-05 16:48 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-05 16:53 UTC, yurishibaev commented
Проверил, все ок

2020-10-05 16:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-06 14:08 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +     sorted.sort( (a, b) => b.localeCompare(a, ['ru', 'en'], {caseFirst: 'upper'}) );
теперь осталась проблема с дублирующимся кодом. Строка 10 идентична строке 12 за исключением порядка пргументов в `localCompare` - это нужно исправить, устранить дубликаты

2020-10-06 14:08 UTC, dosandk requested changes
необходимо исправить `sortStrings`

2020-10-07 14:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 18:39 UTC, dosandk approved these changes
good 👍

2020-10-07 18:40 UTC, merged