решение задачи 5
js-tasks-ru/js-20200928_yuriy-sh pull request #4
Opened 2020-10-17 17:10 UTC by yurishibaev

2020-10-17 17:17 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-18 16:15 UTC, dosandk commented
> Задача 5.1 решена с помощью записи DOM через объекты, а задача 5.2 - через html-строки. Решил последующие решения также делать через html строки, раз уж Вы так всегда показываете в примерах решения. Хотя мне такой способ и не очень нравится, т.к. не объектно ориентированный и легче допустить ошибку, и элементы прописываем прямо в строке, но видимо так в javascript чаще делается. Все равно язык совсем не строгой типизации.

Не совсем понял почемы Вы называете подход с созданием элемента через метод `innerHTML` и шаблонную строку "не объектно ориентированным". К парадигме объектно ориентированности это не имеет слабое отношение. Можете уточнить что Вы имели ввиду?

У шаблонной строки есть ряд преимуществ: 
* она выглядит как обычный `html`, eсли разработчик владеет `html` то вероятность ошибки сводится к минимуму
* если вложенность элементов из которых состоит компонент достоточно глубокая, допустим более 5, до разобраться в DOM элементах, созданных не через шаблонную строку становится очень проблематично

2020-10-18 16:17 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    createEl(name, classNames, parent){
данная обертка не облегчает использование или понимание кода

2020-10-18 16:17 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    createDivEl(classNames, parent){
данная обертка не облегчает использование или понимание кода

2020-10-18 16:18 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        const parentEl = this.createDivEl(['notification', this.type]);
от такого подхода по созданию элементов лучше отказаться в пользу шаблонной строки

2020-10-18 16:20 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        NotificationMessage.hasMessage = true;
Здесь используется статическое свойство класса, но оно отсутствует при объявление. Если быть точнее свойство `hasMessage` объявлено в классе, но без ключевого слова `static`. В результате у нас два свойства с одинаковыми именами, но располагающимися на классе и на инстансе объекта, что может привести к путаннице в коде. Это нужно исправить

2020-10-18 16:21 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    remove(thisEl){
для чего методу `remove` передается аргумент `thisEl`?

2020-10-18 16:22 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    remove(thisEl){
чем значение в `thisEl` отличается от значения в `this.element`?

2020-10-18 16:25 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +            if (item.template) {
этот кусок кода можно упростить. Так как в обоих ветках `if` и `else` происходит `push`, можно сделать вот так:
```
const column = item.template ? [item.id, item.template] : item.id;

return this.columns.push(column);
```

2020-10-18 16:26 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +                ${this.header.reduce((previosValue, column) => {
помните мы обсуждали работу со строками? 
Речь шла о конкатенации (в том числе и о `reduce`) и о создании строки через `map`?

2020-10-18 16:27 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +            function check(first, second) {
данную функцию можно вынести за пределы `sort`, в противном случае она будет создаваться вновь на каждой итерации массива

2020-10-18 16:28 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-10-18 19:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
- should be rendered correctly
- should have default sorting marked by arrow icon
- should sort "desc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal number
- should move arrow icon to the corresponding column after sorting
- should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

2020-10-18 19:13 UTC, yurishibaev commented
> > Задача 5.1 решена с помощью записи DOM через объекты, а задача 5.2 - через html-строки. Решил последующие решения также делать через html строки, раз уж Вы так всегда показываете в примерах решения. Хотя мне такой способ и не очень нравится, т.к. не объектно ориентированный и легче допустить ошибку, и элементы прописываем прямо в строке, но видимо так в javascript чаще делается. Все равно язык совсем не строгой типизации.
> 
> Не совсем понял почемы Вы называете подход с созданием элемента через метод `innerHTML` и шаблонную строку "не объектно ориентированным". К парадигме объектно ориентированности это не имеет слабое отношение. Можете уточнить что Вы имели ввиду?
> 
> У шаблонной строки есть ряд преимуществ:
> 
> * она выглядит как обычный `html`, eсли разработчик владеет `html` то вероятность ошибки сводится к минимуму
> * если вложенность элементов из которых состоит компонент достоточно глубокая, допустим более 5, до разобраться в DOM элементах, созданных не через шаблонную строку становится очень проблематично

Пример.
<div>
<div>
Примитивный пример, просто для наглядности. В строке ошибка. Подобные ошибки пропускаются, и отлавливаются на этапе выполнения. Если использовать методы для работы с DOM, например, document.createElement('div'), то такой ошибки не возникнет. Но, в целом понятно, это мало относится к js, а скорее относится к языкам со строгой типизацией, где лучше работать с объектами по типу document.createElement('div'), а не со строками '<dv>   </div>'.
Но я уже пришел к выводу об использовании шаблонных строк, т.к. для js это лучший вариант.

Прошу зачесть задание 5.1 без переделки на шаблонные строки, чтобы не переписывать.

2020-10-20 19:18 UTC, dosandk approved these changes
Рншения приняты.
Из PR нужно убрать все файлы которые не относятся к решению, иначе система не позволит смержить данный PR

2020-10-20 19:18 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-10-24 21:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
Tooltip компонент
- should be rendered correctly
- should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-10-24 21:48 UTC, dosandk commented
@yurishibaev поправьте пожалуйста тесты

2020-10-28 20:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-28 22:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-30 18:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-01 11:25 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    serverUrl = 'https://course-js.javascript.ru';
данную ссылку лучше держать в константе за пределами клсасса (это на будущее), для данного решения это не сильно принципиально

2020-11-01 11:26 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +        if (!this.link){
такие конструкции лучше заменять на тернарник - будет компактнее и проще для чтения/понимания
```
return this.link 
  ? <a href=${this.link} class='column-chart__link'>View all</a>
  : '';
```

2020-11-01 11:27 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +        response.forEach( item => {
эту операцию лучше разбить на две:
* обработка данных
* создание тимплейта (метод map)

2020-11-01 11:28 UTC, dosandk approved these changes

2020-11-01 11:29 UTC, merged